# Train Contextual Bandits with simple linear, stationary simulation environment

> In this notebook, we'll evaluate the performance of Contextual Bandits in stationary, stochastic environments. These are environments whose statistics (e.g., distribution of rewards) do not change over time

* A linear  environment is an environment where the expected reward for each arm `k` is linearly related to the context features `x`
* Train and evaluate linear and non-linear (neural) Contextual Bandit algorithms
* We'll show that linear-based agents converge faster on such an environment, compared to non-linear agents, becasue the problem is linear (by the reward calculation construction)

### Per-arm environment
In this example we will use the [StationaryStochasticPerArmPyEnvironment](https://github.com/tensorflow/agents/blob/master/tf_agents/bandits/environments/stationary_stochastic_per_arm_py_environment.py) environment to simulate offline training data for training a contextual bandit with **per-arm features**


To initialize the per-arm environment, one has to define functions that generate:

* *global and per-arm features*: These functions have no input parameters and generate a single (global or per-arm) feature vector when called.

* *rewards*: This function takes as parameter the concatenation of a global and a per-arm feature vector, and generates a reward. Basically this is the function that the agent will have to "guess". 

It is worth noting here that in the per-arm case the reward function is identical for every arm. This is a fundamental difference from the classic bandit case, where the agent has to estimate reward functions for each arm independently.

## Load notebook config

* use the prefix defined in `00-env-setup`

In [1]:
VERSION        = "v2"                       # TODO
PREFIX         = f'rec-bandits-{VERSION}'   # TODO

print(f"PREFIX: {PREFIX}")

PREFIX: rec-bandits-v2


In [2]:
# staging GCS
GCP_PROJECTS             = !gcloud config get-value project
PROJECT_ID               = GCP_PROJECTS[0]

# GCS bucket and paths
BUCKET_NAME              = f'{PREFIX}-{PROJECT_ID}-bucket'
BUCKET_URI               = f'gs://{BUCKET_NAME}'

config = !gsutil cat {BUCKET_URI}/config/notebook_env.py
print(config.n)
exec(config.n)


PROJECT_ID               = "hybrid-vertex"
PROJECT_NUM              = "934903580331"
LOCATION                 = "us-central1"

REGION                   = "us-central1"
BQ_LOCATION              = "US"
VPC_NETWORK_NAME         = "ucaip-haystack-vpc-network"

VERTEX_SA                = "934903580331-compute@developer.gserviceaccount.com"

PREFIX                   = "rec-bandits-v2"
VERSION                  = "v2"

BUCKET_NAME              = "rec-bandits-v2-hybrid-vertex-bucket"
BUCKET_URI               = "gs://rec-bandits-v2-hybrid-vertex-bucket"
DATA_GCS_PREFIX          = "data"
DATA_PATH                = "gs://rec-bandits-v2-hybrid-vertex-bucket/data"
VOCAB_SUBDIR             = "vocabs"
VOCAB_FILENAME           = "vocab_dict.pkl"
DATA_PATH_KFP_DEMO       = "gs://rec-bandits-v2-hybrid-vertex-bucket/data/kfp_demo_data/u.data"

VPC_NETWORK_FULL         = "projects/934903580331/global/networks/ucaip-haystack-vpc-network"

BIGQUERY_DATASET_NAME    = "mvlens_rec_bandits_v2"
BIGQUERY_TABLE_NA

## imports

In [3]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

In [4]:
import functools
from collections import defaultdict
from typing import Callable, Dict, List, Optional, TypeVar
from datetime import datetime
import time
from pprint import pprint
import pickle as pkl

from tqdm import tqdm

# logging
import logging
logging.disable(logging.WARNING)

import warnings
warnings.filterwarnings('ignore')

import matplotlib.pyplot as plt
import numpy as np

# google cloud
from google.cloud import aiplatform, storage

# tensorflow
import tensorflow as tf
# from tf_agents.agents import TFAgent

from tf_agents.bandits.environments import stationary_stochastic_per_arm_py_environment as p_a_env
from tf_agents.bandits.metrics import tf_metrics as tf_bandit_metrics
from tf_agents.drivers import dynamic_step_driver
from tf_agents.environments import tf_py_environment
from tf_agents.replay_buffers import tf_uniform_replay_buffer
from tf_agents.specs import tensor_spec
from tf_agents.trajectories import time_step as ts

from tf_agents.bandits.agents import lin_ucb_agent
from tf_agents.bandits.agents import linear_thompson_sampling_agent as lin_ts_agent
from tf_agents.bandits.agents import neural_epsilon_greedy_agent
from tf_agents.bandits.agents import neural_linucb_agent
from tf_agents.bandits.networks import global_and_arm_feature_network
from tf_agents.bandits.policies import policy_utilities

from tf_agents.bandits.specs import utils as bandit_spec_utils
from tf_agents.trajectories import trajectory

from tf_agents.bandits.replay_buffers import bandit_replay_buffer
from tf_agents.drivers import dynamic_step_driver
from tf_agents.eval import metric_utils
# from tf_agents.google.metrics import export_utils
from tf_agents.metrics import export_utils
from tf_agents.metrics import tf_metrics
from tf_agents.policies import policy_saver

# GPU
from numba import cuda 
import gc

import sys
sys.path.append("..")

# this repo
from src.per_arm_rl import data_utils
from src.per_arm_rl import data_config
from src.per_arm_rl import train_utils as train_utils
from src.per_arm_rl import policy_util

# tf exceptions and vars
if tf.__version__[0] != "2":
    raise Exception("The trainer only runs with TensorFlow version 2.")

T = TypeVar("T")

In [5]:
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))

Num GPUs Available:  1


In [7]:
device = cuda.get_current_device()
device.reset()
gc.collect()

14

In [9]:
# cloud storage client
storage_client = storage.Client(project=PROJECT_ID)

# Vertex client
aiplatform.init(project=PROJECT_ID, location=LOCATION)

# Data prep

## Read TF Records (for testing)

In [10]:
DATA_TAG = "movielens-100k" # movielens-100k | movielens-1m

print(f"DATA_TAG: {DATA_TAG}")

! gsutil ls $DATA_PATH/$DATA_TAG

DATA_TAG: movielens-100k
gs://rec-bandits-v2-hybrid-vertex-bucket/data/movielens-100k/vocab_dict.pkl
gs://rec-bandits-v2-hybrid-vertex-bucket/data/movielens-100k/all/
gs://rec-bandits-v2-hybrid-vertex-bucket/data/movielens-100k/train/
gs://rec-bandits-v2-hybrid-vertex-bucket/data/movielens-100k/val/


In [11]:
options = tf.data.Options()
options.experimental_distribute.auto_shard_policy = tf.data.experimental.AutoShardPolicy.AUTO

In [12]:
SPLIT = "train" # "train" | "val"

train_files = []
for blob in storage_client.list_blobs(f"{BUCKET_NAME}", prefix=f'{DATA_GCS_PREFIX}/{DATA_TAG}/{SPLIT}'):
    if '.tfrecord' in blob.name:
        train_files.append(blob.public_url.replace("https://storage.googleapis.com/", "gs://"))
        
train_files

['gs://rec-bandits-v2-hybrid-vertex-bucket/data/movielens-100k/train/ml-100k-ratings-train-01-of-05.tfrecord',
 'gs://rec-bandits-v2-hybrid-vertex-bucket/data/movielens-100k/train/ml-100k-ratings-train-02-of-05.tfrecord',
 'gs://rec-bandits-v2-hybrid-vertex-bucket/data/movielens-100k/train/ml-100k-ratings-train-03-of-05.tfrecord',
 'gs://rec-bandits-v2-hybrid-vertex-bucket/data/movielens-100k/train/ml-100k-ratings-train-04-of-05.tfrecord']

In [13]:
train_dataset = tf.data.TFRecordDataset(train_files)
train_dataset = train_dataset.map(data_utils.parse_tfrecord)

for x in train_dataset.batch(1).take(1):
    pprint(x)

{'bucketized_user_age': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([45.], dtype=float32)>,
 'movie_genres': <tf.Tensor: shape=(1, 1), dtype=int64, numpy=array([[7]])>,
 'movie_id': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'357'], dtype=object)>,
 'timestamp': <tf.Tensor: shape=(1,), dtype=int64, numpy=array([879024327])>,
 'user_id': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'138'], dtype=object)>,
 'user_occupation_text': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'doctor'], dtype=object)>,
 'user_rating': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([4.], dtype=float32)>}


### get vocab

In [14]:
GENERATE_VOCABS = False

print(f"GENERATE_VOCABS: {GENERATE_VOCABS}")

GENERATE_VOCABS: False


In [15]:
if not GENERATE_VOCABS:

    EXISTING_VOCAB_FILE = f'gs://{BUCKET_NAME}/{DATA_GCS_PREFIX}/{DATA_TAG}/{VOCAB_FILENAME}'
    print(f"Downloading vocab...")
    
    os.system(f'gsutil -q cp {EXISTING_VOCAB_FILE} .')
    print(f"Downloaded vocab from: {EXISTING_VOCAB_FILE}\n")

    filehandler = open(VOCAB_FILENAME, 'rb')
    vocab_dict = pkl.load(filehandler)
    filehandler.close()
    
    for key in vocab_dict.keys():
        pprint(key)

Downloaded vocab from: gs://rec-bandits-v2-hybrid-vertex-bucket/data/movielens-100k/vocab_dict.pkl

'movie_id'
'user_id'
'user_occupation_text'
'movie_genres'
'bucketized_user_age'
'max_timestamp'
'min_timestamp'
'timestamp_buckets'


# Global & Per-Arm feature embedding models 

In [16]:
NUM_OOV_BUCKETS        = 1
GLOBAL_EMBEDDING_SIZE  = 16
MV_EMBEDDING_SIZE      = 32 #32

In [17]:
# test emb models
for i in range(1):
    
    iterator = iter(train_dataset.batch(1))
    data = next(iterator)

# data

In [18]:
from src.perarm_features import emb_features as emb_features

embs = emb_features.EmbeddingModel(
    vocab_dict = vocab_dict,
    num_oov_buckets = NUM_OOV_BUCKETS,
    global_emb_size = GLOBAL_EMBEDDING_SIZE,
    mv_emb_size = MV_EMBEDDING_SIZE,
)

embs

In [19]:
test_globals = embs._get_global_context_features(data)

GLOBAL_DIM = test_globals.shape[1]            
# shape checks out at batch_dim, nactions, arm feats
print(f"GLOBAL_DIM: {GLOBAL_DIM}")

test_globals

GLOBAL_DIM: 64


<tf.Tensor: shape=(1, 64), dtype=float32, numpy=
array([[-0.0184383 , -0.03894822,  0.00513189,  0.03321711,  0.03478311,
        -0.04066921,  0.03618351, -0.00489004, -0.02246409, -0.01614964,
        -0.00805875,  0.02650708, -0.04822195,  0.01572521,  0.03252577,
        -0.00887423, -0.0120305 , -0.04590234, -0.04578064,  0.00227224,
         0.0214457 , -0.0148605 ,  0.02696443,  0.01265207, -0.04214443,
        -0.01604214, -0.043206  , -0.04495594,  0.014376  , -0.01676066,
         0.00597216, -0.00401383,  0.00072857, -0.02916597,  0.00104284,
         0.02768863, -0.03252157,  0.04648724, -0.02414525, -0.02835464,
         0.02331436,  0.0498654 ,  0.0087239 , -0.02322137, -0.0423955 ,
         0.03037107,  0.02202067, -0.02039803,  0.03746719, -0.00310605,
        -0.0202341 , -0.02202946, -0.01585388,  0.02658557, -0.00865828,
         0.0245355 , -0.00632703, -0.02612565, -0.02200326, -0.01381309,
         0.02327615, -0.00941961,  0.01031157,  0.00667394]],
      dtype=f

In [20]:
test_arms = embs._get_per_arm_features(data)

PER_ARM_DIM = test_arms.shape[1]            
# shape checks out at batch_dim, nactions, arm feats
print(f"PER_ARM_DIM: {PER_ARM_DIM}")

test_arms

PER_ARM_DIM: 64


<tf.Tensor: shape=(1, 64), dtype=float32, numpy=
array([[-0.04602586, -0.03587122,  0.00030255, -0.00592788,  0.02938599,
         0.03024001, -0.02551819, -0.01284537, -0.04472363, -0.02767679,
         0.04128381, -0.01166994, -0.04724962,  0.03400481,  0.01376344,
        -0.04117516, -0.02969636, -0.03938909, -0.00737112, -0.01792452,
        -0.02786292, -0.03012486,  0.03586279,  0.04632575, -0.02388661,
         0.03555742,  0.04626267,  0.00156311,  0.01962711, -0.04815055,
         0.04863915, -0.02275487, -0.01470612, -0.00218835,  0.03149606,
        -0.01080934,  0.0319992 ,  0.03259032, -0.02268947,  0.04576692,
         0.01431593,  0.02255676,  0.02570519, -0.03895449,  0.02913688,
         0.04866644,  0.02898869, -0.03645029, -0.00176028,  0.04871298,
         0.02291036,  0.01141062, -0.02997943, -0.03081605, -0.00878236,
        -0.01974301,  0.04062701,  0.04069677, -0.00850657,  0.00493377,
        -0.02962869,  0.03197886, -0.0202675 , -0.02305681]],
      dtype=f

# Sampling and reward functions

The preproccesing layers will ultimately feed the two sampling functions described below. These sampling functions will be used to create [trajectories](https://github.com/tensorflow/agents/blob/master/tf_agents/trajectories/trajectory.py#L36) (i.e., the training examples for our model)

`global_context_sampling_fn`: 
* A function that outputs a random 1d array or list of ints or floats
* This output is the global context. Its shape and type must be consistent across calls.

`arm_context_sampling_fn`: 
* A function that outputs a random 1 array or list of ints or floats (same type as the output of `global_context_sampling_fn`). 
* This output is the per-arm context. Its shape must be consistent across calls.

`reward_fn`: function takes the concatenation of a global and a per-arm feature, and outputs a possibly random reward.

In [21]:
BATCH_SIZE      = 128
EVAL_BATCH_SIZE = 1
NUM_ACTIONS     = 20

## Sampling global context

In [22]:
def example_global_context_sampling_fn():
    # return np.random.randint(0, 10, [2])  # 2-dimensional global features.
    return np.random.randint(-1, 1, [GLOBAL_DIM]).astype(np.float32)

example_global_context_sampling_fn()

array([ 0.,  0.,  0., -1.,  0., -1.,  0.,  0., -1.,  0.,  0.,  0.,  0.,
        0., -1., -1., -1.,  0.,  0., -1., -1., -1., -1., -1., -1., -1.,
        0., -1., -1., -1.,  0., -1., -1.,  0.,  0., -1., -1.,  0., -1.,
       -1.,  0., -1., -1.,  0.,  0.,  0., -1.,  0., -1., -1.,  0.,  0.,
        0., -1., -1.,  0., -1., -1.,  0.,  0.,  0., -1.,  0., -1.],
      dtype=float32)

In [23]:
global_iterator = iter(train_dataset.batch(1).repeat())

def global_context_sampling_fn():
    
    data = next(global_iterator)
    
    return embs._get_global_context_features(data)[0].numpy()

In [24]:
test_global_sampling = global_context_sampling_fn()
print(f"shape: {test_global_sampling.shape}")

test_global_sampling

shape: (64,)


array([-0.0184383 , -0.03894822,  0.00513189,  0.03321711,  0.03478311,
       -0.04066921,  0.03618351, -0.00489004, -0.02246409, -0.01614964,
       -0.00805875,  0.02650708, -0.04822195,  0.01572521,  0.03252577,
       -0.00887423, -0.0120305 , -0.04590234, -0.04578064,  0.00227224,
        0.0214457 , -0.0148605 ,  0.02696443,  0.01265207, -0.04214443,
       -0.01604214, -0.043206  , -0.04495594,  0.014376  , -0.01676066,
        0.00597216, -0.00401383,  0.00072857, -0.02916597,  0.00104284,
        0.02768863, -0.03252157,  0.04648724, -0.02414525, -0.02835464,
        0.02331436,  0.0498654 ,  0.0087239 , -0.02322137, -0.0423955 ,
        0.03037107,  0.02202067, -0.02039803,  0.03746719, -0.00310605,
       -0.0202341 , -0.02202946, -0.01585388,  0.02658557, -0.00865828,
        0.0245355 , -0.00632703, -0.02612565, -0.02200326, -0.01381309,
        0.02327615, -0.00941961,  0.01031157,  0.00667394], dtype=float32)

## Sampling arm context

In [25]:
def example_arm_context_sampling_fn():
    # return np.random.randint(-3, 4, [3])  # 3-dimensional arm features.
    return np.random.randint(-2, 3, [PER_ARM_DIM]).astype(np.float32)

example_arm_context_sampling_fn()

array([ 1.,  0.,  2.,  1.,  2., -2., -1.,  2.,  2.,  0.,  1., -1.,  2.,
        1., -2., -2., -2., -1.,  0.,  1.,  2., -1., -1.,  2., -2.,  0.,
       -1., -2., -2.,  1.,  1.,  0., -2.,  1.,  2.,  0.,  1.,  1., -1.,
       -1.,  0., -2.,  2.,  0.,  0., -2., -2., -1., -1.,  0., -1.,  1.,
        0., -2.,  0., -1.,  0.,  0., -2., -1., -1.,  1.,  2.,  2.],
      dtype=float32)

In [26]:
arm_iterator = iter(train_dataset.batch(1).repeat())
# arm_iterator = iter(train_dataset.repeat())

def arm_context_sampling_fn():
    
    data = next(arm_iterator)
    
    return embs._get_per_arm_features(data)[0].numpy()

In [27]:
test_arm_sampling = arm_context_sampling_fn()
print(f"shape: {test_arm_sampling.shape}")

test_arm_sampling

shape: (64,)


array([-0.04602586, -0.03587122,  0.00030255, -0.00592788,  0.02938599,
        0.03024001, -0.02551819, -0.01284537, -0.04472363, -0.02767679,
        0.04128381, -0.01166994, -0.04724962,  0.03400481,  0.01376344,
       -0.04117516, -0.02969636, -0.03938909, -0.00737112, -0.01792452,
       -0.02786292, -0.03012486,  0.03586279,  0.04632575, -0.02388661,
        0.03555742,  0.04626267,  0.00156311,  0.01962711, -0.04815055,
        0.04863915, -0.02275487, -0.01470612, -0.00218835,  0.03149606,
       -0.01080934,  0.0319992 ,  0.03259032, -0.02268947,  0.04576692,
        0.01431593,  0.02255676,  0.02570519, -0.03895449,  0.02913688,
        0.04866644,  0.02898869, -0.03645029, -0.00176028,  0.04871298,
        0.02291036,  0.01141062, -0.02997943, -0.03081605, -0.00878236,
       -0.01974301,  0.04062701,  0.04069677, -0.00850657,  0.00493377,
       -0.02962869,  0.03197886, -0.0202675 , -0.02305681], dtype=float32)

### Reward function 

> compute the dot product between global user context features and arm context features

In this environment, the reward function will take as input the concatenation of the global and arm features generated from the provided sampling functions. See it used in the environment's `_apply_action()` function [here](https://github.com/tensorflow/agents/blob/master/tf_agents/bandits/environments/stationary_stochastic_per_arm_py_environment.py#L170C18-L170C28)

```python
feat_concat = np.concatenate((test_global_sampling, test_arm_sampling))
reward = np.dot(feat_concat[:GLOBAL_DIM], feat_concat[PER_ARM_DIM:])
```

In [28]:
test_global_sampling #[0]

array([-0.0184383 , -0.03894822,  0.00513189,  0.03321711,  0.03478311,
       -0.04066921,  0.03618351, -0.00489004, -0.02246409, -0.01614964,
       -0.00805875,  0.02650708, -0.04822195,  0.01572521,  0.03252577,
       -0.00887423, -0.0120305 , -0.04590234, -0.04578064,  0.00227224,
        0.0214457 , -0.0148605 ,  0.02696443,  0.01265207, -0.04214443,
       -0.01604214, -0.043206  , -0.04495594,  0.014376  , -0.01676066,
        0.00597216, -0.00401383,  0.00072857, -0.02916597,  0.00104284,
        0.02768863, -0.03252157,  0.04648724, -0.02414525, -0.02835464,
        0.02331436,  0.0498654 ,  0.0087239 , -0.02322137, -0.0423955 ,
        0.03037107,  0.02202067, -0.02039803,  0.03746719, -0.00310605,
       -0.0202341 , -0.02202946, -0.01585388,  0.02658557, -0.00865828,
        0.0245355 , -0.00632703, -0.02612565, -0.02200326, -0.01381309,
        0.02327615, -0.00941961,  0.01031157,  0.00667394], dtype=float32)

In [29]:
test_arm_sampling #[0]

array([-0.04602586, -0.03587122,  0.00030255, -0.00592788,  0.02938599,
        0.03024001, -0.02551819, -0.01284537, -0.04472363, -0.02767679,
        0.04128381, -0.01166994, -0.04724962,  0.03400481,  0.01376344,
       -0.04117516, -0.02969636, -0.03938909, -0.00737112, -0.01792452,
       -0.02786292, -0.03012486,  0.03586279,  0.04632575, -0.02388661,
        0.03555742,  0.04626267,  0.00156311,  0.01962711, -0.04815055,
        0.04863915, -0.02275487, -0.01470612, -0.00218835,  0.03149606,
       -0.01080934,  0.0319992 ,  0.03259032, -0.02268947,  0.04576692,
        0.01431593,  0.02255676,  0.02570519, -0.03895449,  0.02913688,
        0.04866644,  0.02898869, -0.03645029, -0.00176028,  0.04871298,
        0.02291036,  0.01141062, -0.02997943, -0.03081605, -0.00878236,
       -0.01974301,  0.04062701,  0.04069677, -0.00850657,  0.00493377,
       -0.02962869,  0.03197886, -0.0202675 , -0.02305681], dtype=float32)

In [30]:
HIDDEN_PARAM = list(np.random.randint(0, 10, [GLOBAL_DIM + PER_ARM_DIM]))

class LinearNormalReward(object):
    def __init__(self, theta):
        self.theta = theta

    def __call__(self, x):
        mu = np.dot(x, self.theta)
        return np.random.normal(mu, 1)
    
reward_fn = LinearNormalReward(HIDDEN_PARAM)

## Initialize environment

In [31]:
print(f"BATCH_SIZE      : {BATCH_SIZE}")
print(f"EVAL_BATCH_SIZE : {EVAL_BATCH_SIZE}")
print(f"NUM_ACTIONS     : {NUM_ACTIONS}")
print(f"GLOBAL_DIM      : {GLOBAL_DIM}")
print(f"PER_ARM_DIM     : {PER_ARM_DIM}")

BATCH_SIZE      : 128
EVAL_BATCH_SIZE : 1
NUM_ACTIONS     : 20
GLOBAL_DIM      : 64
PER_ARM_DIM     : 64


In [32]:
per_arm_py_env = p_a_env.StationaryStochasticPerArmPyEnvironment(
    global_context_sampling_fn=global_context_sampling_fn,
    arm_context_sampling_fn=arm_context_sampling_fn,
    max_num_actions=NUM_ACTIONS,
    reward_fn=reward_fn,
    batch_size=BATCH_SIZE
)
per_arm_tf_env = tf_py_environment.TFPyEnvironment(per_arm_py_env)

In [33]:
# print('observation spec: ', per_arm_tf_env.observation_spec())
# print('\nAn observation: ', per_arm_tf_env.reset().observation)

action = tf.zeros(BATCH_SIZE, dtype=tf.int32)
time_step = per_arm_tf_env.step(action)
print('\nRewards after taking an action: ', time_step.reward)


Rewards after taking an action:  tf.Tensor(
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0.], shape=(128,), dtype=float32)


In [34]:
observation_spec = per_arm_tf_env.observation_spec()
# observation_spec

In [35]:
time_step_spec = ts.time_step_spec(observation_spec)
# time_step_spec

In [36]:
action_spec = tensor_spec.BoundedTensorSpec(
    dtype=tf.int32, 
    shape=(), 
    minimum=0, 
    maximum=NUM_ACTIONS - 1
)
# action_spec

## Define Agent Policy

In [37]:
# ================================
# Agents
# ================================
AGENT_TYPE      = 'NeuralLinUCB' # 'LinUCB' | 'LinTS |, 'epsGreedy' | 'NeuralLinUCB'

# Parameters for linear agents (LinUCB and LinTS).
AGENT_ALPHA     = 0.1

# Parameters for neural agents (NeuralEpsGreedy and NerualLinUCB).
EPSILON         = 0.01
LR              = 0.05

# Parameters for NeuralLinUCB
ENCODING_DIM    = 1
EPS_PHASE_STEPS = 1000

# ================================
# Agent's Preprocess Network
# ================================
GLOBAL_LAYERS   = [64, 32, 16] # beginning should be of size: GLOBAL_DIM
ARM_LAYERS      = [64, 32, 16] # beginning should be of size: PER_ARM_DIM
COMMON_LAYERS   = [16, 8]

NETWORK_TYPE    = "dotproduct" # 'dotproduct' | 'commontower'

if AGENT_TYPE == 'NeuralLinUCB':
    NETWORK_TYPE = 'commontower'
    ENCODING_DIM = COMMON_LAYERS[-1]

HPARAMS = {  # TODO - streamline and consolidate
    "batch_size": BATCH_SIZE,
    "eval_batch_size" : EVAL_BATCH_SIZE,
    "num_actions": NUM_ACTIONS,
    "model_type": AGENT_TYPE,
    "network_type": NETWORK_TYPE,
    "global_layers": GLOBAL_LAYERS,
    "per_arm_layers": ARM_LAYERS,
    "common_layers": COMMON_LAYERS,
    "learning_rate": LR,
    "epsilon": EPSILON,
}
pprint(HPARAMS)

{'batch_size': 128,
 'common_layers': [16, 8],
 'epsilon': 0.01,
 'eval_batch_size': 1,
 'global_layers': [64, 32, 16],
 'learning_rate': 0.05,
 'model_type': 'NeuralLinUCB',
 'network_type': 'commontower',
 'num_actions': 20,
 'per_arm_layers': [64, 32, 16]}


In [38]:
from src.perarm_features import agent_factory as agent_factory

global_step = tf.compat.v1.train.get_or_create_global_step()

agent = agent_factory.PerArmAgentFactory._get_agent(
    agent_type = AGENT_TYPE,
    network_type = NETWORK_TYPE,
    time_step_spec = time_step_spec,
    action_spec = action_spec,
    observation_spec=observation_spec,
    global_layers = GLOBAL_LAYERS,
    arm_layers = ARM_LAYERS,
    common_layers = COMMON_LAYERS,
    agent_alpha = AGENT_ALPHA,
    learning_rate = LR,
    epsilon = EPSILON,
    train_step_counter = global_step,
    output_dim = ENCODING_DIM,
    eps_phase_steps = EPS_PHASE_STEPS,
    summarize_grads_and_vars = True,
    debug_summaries = True
)
      
# agent.initialize()
print(f'agent: {agent.name}')

# if network:
#     print(f"Network: {network}")

if NETWORK_TYPE:
    print(f"Network: {NETWORK_TYPE}")

agent: neural_linucb_agent
Network: commontower


### The Flow of Training Data

look at the data specification in the agent. The training_data_spec attribute of the agent specifies what elements and structure the training data should have.

In [39]:
print('training data spec: ', agent.training_data_spec)

training data spec:  Trajectory(
{'action': BoundedTensorSpec(shape=(), dtype=tf.int32, name='action', minimum=array(0, dtype=int32), maximum=array(19, dtype=int32)),
 'discount': BoundedTensorSpec(shape=(), dtype=tf.float32, name='discount', minimum=array(0., dtype=float32), maximum=array(1., dtype=float32)),
 'next_step_type': TensorSpec(shape=(), dtype=tf.int32, name='step_type'),
 'observation': DictWrapper({'global': TensorSpec(shape=(64,), dtype=tf.float32, name=None)}),
 'policy_info': PerArmPolicyInfo(log_probability=(), predicted_rewards_mean=TensorSpec(shape=(20,), dtype=tf.float32, name=None), multiobjective_scalarized_predicted_rewards_mean=(), predicted_rewards_optimistic=(), predicted_rewards_sampled=(), bandit_policy_type=(), chosen_arm_features=TensorSpec(shape=(64,), dtype=tf.float32, name=None)),
 'reward': TensorSpec(shape=(), dtype=tf.float32, name='reward'),
 'step_type': TensorSpec(shape=(), dtype=tf.int32, name='step_type')})


In [40]:
def _all_rewards(observation, hidden_param):
    """Outputs rewards for all actions, given an observation."""
    hidden_param = tf.cast(hidden_param, dtype=tf.float32)
    global_obs = observation[bandit_spec_utils.GLOBAL_FEATURE_KEY]
    per_arm_obs = observation[bandit_spec_utils.PER_ARM_FEATURE_KEY]
    num_actions = tf.shape(per_arm_obs)[1]
    tiled_global = tf.tile(
        tf.expand_dims(global_obs, axis=1), [1, num_actions, 1]
    )
    concatenated = tf.concat([tiled_global, per_arm_obs], axis=-1)
    rewards = tf.linalg.matvec(concatenated, hidden_param)
    return rewards

def optimal_reward(observation):
    """
    Outputs the maximum expected reward 
    for every element in the batch.
    """
    return tf.reduce_max(_all_rewards(observation, HIDDEN_PARAM), axis=1)

regret_metric = tf_bandit_metrics.RegretMetric(optimal_reward)

In [41]:
def optimal_action(observation, hidden_param):
    
    return tf.argmax(
        _all_rewards(observation, hidden_param), axis=1, output_type=tf.int32
    )

optimal_action_fn = functools.partial(
    optimal_action, hidden_param=HIDDEN_PARAM
)

suboptimal_arms_metric = tf_bandit_metrics.SuboptimalArmsMetric(
    optimal_action_fn
)

In [42]:
metrics = [regret_metric, suboptimal_arms_metric]
metrics

# Training

In [43]:
from src.per_arm_rl import trainer_baseline

## Vertex AI Experiments

In [44]:
EXPERIMENT_NAME   = f'02-perarm-stationary-env-{PREFIX}'

# new experiment
invoke_time       = time.strftime("%Y%m%d-%H%M%S")
RUN_NAME          = f'run-{invoke_time}'

BASE_OUTPUT_DIR   = f'{BUCKET_URI}/{EXPERIMENT_NAME}/{RUN_NAME}'
LOG_DIR           = f"{BASE_OUTPUT_DIR}/logs"
ROOT_DIR          = f"{BASE_OUTPUT_DIR}/root"       # Root directory for writing logs/summaries/checkpoints.
ARTIFACTS_DIR     = f"{BASE_OUTPUT_DIR}/artifacts"  # Where the trained model will be saved and restored.

# aiplatform.init(
#     project=PROJECT_ID,
#     location=REGION,
#     experiment=EXPERIMENT_NAME
# )

print(f"EXPERIMENT_NAME   : {EXPERIMENT_NAME}")
print(f"RUN_NAME          : {RUN_NAME}\n")
print(f"BASE_OUTPUT_DIR   : {BASE_OUTPUT_DIR}")
print(f"LOG_DIR           : {LOG_DIR}")
print(f"ROOT_DIR          : {ROOT_DIR}")
print(f"ARTIFACTS_DIR     : {ARTIFACTS_DIR}")

EXPERIMENT_NAME   : 02-perarm-stationary-env-rec-bandits-v2
RUN_NAME          : run-20240214-171810

BASE_OUTPUT_DIR   : gs://rec-bandits-v2-hybrid-vertex-bucket/02-perarm-stationary-env-rec-bandits-v2/run-20240214-171810
LOG_DIR           : gs://rec-bandits-v2-hybrid-vertex-bucket/02-perarm-stationary-env-rec-bandits-v2/run-20240214-171810/logs
ROOT_DIR          : gs://rec-bandits-v2-hybrid-vertex-bucket/02-perarm-stationary-env-rec-bandits-v2/run-20240214-171810/root
ARTIFACTS_DIR     : gs://rec-bandits-v2-hybrid-vertex-bucket/02-perarm-stationary-env-rec-bandits-v2/run-20240214-171810/artifacts


### Create TensorBoard

In [45]:
NEW_TENSORBOARD = True

In [46]:
if NEW_TENSORBOARD:
    # create new TB instance
    TENSORBOARD_DISPLAY_NAME=f"{EXPERIMENT_NAME}"

    tensorboard = aiplatform.Tensorboard.create(
        display_name=TENSORBOARD_DISPLAY_NAME
        , project=PROJECT_ID
        , location=REGION
    )

    TB_RESOURCE_NAME = tensorboard.resource_name
else:
    # use existing TB instance
    # TB_RESOURCE_NAME = 'projects/934903580331/locations/us-central1/tensorboards/XXXXXXX' # TODO
    tensorboard = aiplatform.Tensorboard(
        tensorboard_name=TB_RESOURCE_NAME
    )

TB_ID = TB_RESOURCE_NAME.split('/')[-1]

print(f"TB_RESOURCE_NAME : {TB_RESOURCE_NAME}")
print(f"TB display name  : {tensorboard.display_name}")
print(f"TB_ID            : {TB_ID}")

TB_RESOURCE_NAME : projects/934903580331/locations/us-central1/tensorboards/2787486276784226304
TB display name  : 02-perarm-stationary-env-rec-bandits-v2
TB_ID            : 2787486276784226304


## Trainer loop

In [47]:
aiplatform.init(
    project=PROJECT_ID,
    location=REGION,
    experiment=EXPERIMENT_NAME,
    # experiment_tensorboard=TB_ID
)

In [48]:
TRAINING_LOOPS = 50
STEPS_PER_LOOP = 1
LOG_INTERVAL = TRAINING_LOOPS // 5

print(f'LOG_INTERVAL: {LOG_INTERVAL}')

LOG_INTERVAL: 5


In [49]:
metrics

In [50]:
#start the timer and training
start_time = time.time()

trainer_baseline.train(
    # root_dir=LOG_DIR,
    artifact_dir=ARTIFACTS_DIR,
    log_dir=LOG_DIR,
    agent=agent,
    environment=per_arm_tf_env,
    training_loops=TRAINING_LOOPS,
    steps_per_loop=STEPS_PER_LOOP,
    additional_metrics=metrics,
    save_policy=False,
    log_interval=LOG_INTERVAL
)

end_time = time.time()
runtime_mins = int((end_time - start_time) / 60)
print(f"train runtime_mins: {runtime_mins}")

step = 0: train loss = 4.880000114440918
step = 10: train loss = 5.769999980926514
step = 20: train loss = 3.009999990463257
step = 30: train loss = 1.809999942779541
step = 40: train loss = 1.4900000095367432
train runtime_mins: 17


## Evaluate trained policy with TensorBoard

<img src="imgs/linear_ss_env_train.png" 
     align="center" 
     width="850"
     height="850"/>

In [53]:
%load_ext tensorboard
# %reload_ext tensorboard

In [54]:
%tensorboard --logdir=$LOG_DIR 

**Finished**